'use client';
import { useState } from 'react';
import { motion } from 'framer-motion';
import { MapPin, CalendarDays, Clock, ChevronDown } from 'lucide-react';

export default function Home(){
 const [entered,setEntered]=useState(false); const [ride,setRide]=useState(8);
 if(!entered) return <main className="gate"><div className="sun"/><div className="cactus c1">🌵</div><div className="cactus c2">🌵</div><motion.div className="rider" initial={{x:-300}} animate={{x:0}} transition={{duration:2}}>🐎</motion.div><div className="gateWood"><span>FAZENDA</span></div><motion.div className="intro" initial={{opacity:0,y:30}} animate={{opacity:1,y:0}} transition={{delay:1}}><small>APERREIE NÃO, CHEGUE MAIS!</small><h1>O Sertão de<br/><b>Miguel</b></h1><p>Prepare o coração e ajeite o chapéu.<br/>Tem festa boa chegando no terreiro!</p><button onClick={()=>setEntered(true)}>ABRIR A PORTEIRA</button></motion.div></main>;
 return <main><section className="hero"><div className="stars">✦　·　✧　·　✦</div><p className="eyebrow">UM DIA ARRETADO ESTÁ CHEGANDO</p><h1>Nosso pequeno<br/><em>Vaqueiro</em></h1><div className="age"><strong>6</strong><span>ANOS<br/>DE AVENTURA</span></div><p className="copy">No meio da caatinga, onde o sol pinta o céu de ouro,<br/>um pequeno vaqueiro prepara a maior aventura do sertão.</p><ChevronDown/></section><section className="details"><p className="eyebrow">MARQUE NA FOLHINHA</p><h2>O grande dia</h2><div className="cards"><article><CalendarDays/><b>24</b><span>OUTUBRO · 2026</span></article><article><Clock/><b>16:00</b><span>ATÉ O SOL SE PÔR</span></article><article><MapPin/><b>Fazenda<br/>Boa Esperança</b><span>SERTÃO · PE</span></article></div></section><section className="journey"><p className="eyebrow">A MISSÃO DO VAQUEIRO</p><h2>Leve Miguel até o <em>terreiro da festa</em></h2><p>Segure as rédeas e conduza nosso vaqueirinho pelo sertão.</p><div className="trail"><div className="trailSky">☀️　　🌵　　　　　🌵　　　🏡</div><motion.div className="horse" animate={{left:`${ride}%`}}>🐎</motion.div><div className="road"/></div><div className="controls"><button onClick={()=>setRide(Math.max(4,ride-8))}>←</button><button onClick={()=>setRide(Math.min(88,ride+8))}>CONDUZIR O CAVALO</button><button onClick={()=>setRide(Math.min(88,ride+8))}>→</button></div>{ride>=88&&<motion.div initial={{scale:0}} animate={{scale:1}} className="arrived">🎉 Chegamos ao terreiro! A festa vai começar!</motion.div>}</section><section className="rsvp"><p className="eyebrow">CONFIRME SUA PRESENÇA</p><h2>Você é nosso<br/><em>convidado especial</em></h2><p>Vai ser bom demais ter você nessa aventura.</p><button>EU VOU PRA FESTA!</button></section><footer>Desenvolvido por Anderson Jhonatan da K2 Tech</footer></main>
}